export interface ApiError {
  correlationId: string;
  code: string;
  message: string;
  timestamp: string;
}

export const ErrorCode = {
  TENANT_NOT_FOUND: 'TENANT_NOT_FOUND',
  CURRENCY_MISMATCH: 'CURRENCY_MISMATCH',
  INVALID_CURRENCY: 'INVALID_CURRENCY',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  RENTER_NOT_REGISTERED: 'RENTER_NOT_REGISTERED',
  RENTER_DISABLED: 'RENTER_DISABLED',
  RENTER_ALREADY_REGISTERED: 'RENTER_ALREADY_REGISTERED',
  BOT_SECRET_INVALID: 'BOT_SECRET_INVALID',
  SLUG_TAKEN: 'SLUG_TAKEN',
  FORBIDDEN: 'FORBIDDEN',
  IMPERSONATION_FORBIDDEN: 'IMPERSONATION_FORBIDDEN',
  ORG_NOT_FOUND: 'ORG_NOT_FOUND',
  ORG_SUSPENDED: 'ORG_SUSPENDED',
  CONSENT_REQUIRED: 'CONSENT_REQUIRED',
  RE_CONSENT_REQUIRED: 'RE_CONSENT_REQUIRED',
  STATION_NOT_FOUND: 'STATION_NOT_FOUND',
  STATION_AUTOLOCK_INVALID: 'STATION_AUTOLOCK_INVALID',
  STATION_TOKEN_REF_EMPTY: 'STATION_TOKEN_REF_EMPTY',
  STATION_HA_URL_INVALID: 'STATION_HA_URL_INVALID',
  LOCKER_NOT_FOUND: 'LOCKER_NOT_FOUND',
  LOCKER_STATION_OFFLINE: 'LOCKER_STATION_OFFLINE',
  LOCKER_OPEN_FAILED: 'LOCKER_OPEN_FAILED',
  LOCKER_CLOSE_FAILED: 'LOCKER_CLOSE_FAILED',
  DUPLICATE_TARIFF: 'DUPLICATE_TARIFF',
  TARIFF_NOT_FOUND: 'TARIFF_NOT_FOUND',
  TARIFF_DURATION_INVALID: 'TARIFF_DURATION_INVALID',
  TARIFF_PRICE_INVALID: 'TARIFF_PRICE_INVALID',
  TARIFF_DAY_TYPE_INVALID: 'TARIFF_DAY_TYPE_INVALID',
  WEBHOOK_SECRET_INVALID: 'WEBHOOK_SECRET_INVALID',
  KIT_NOT_FOUND: 'KIT_NOT_FOUND',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
