export interface ApiError {
  correlationId: string;
  code: string;
  message: string;
  timestamp: string;
}

export const ErrorCode = {
  TENANT_NOT_FOUND: 'TENANT_NOT_FOUND',
  CURRENCY_MISMATCH: 'CURRENCY_MISMATCH',
  INVALID_CURRENCY: 'INVALID_CURRENCY',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  RENTER_NOT_REGISTERED: 'RENTER_NOT_REGISTERED',
  RENTER_DISABLED: 'RENTER_DISABLED',
  RENTER_ALREADY_REGISTERED: 'RENTER_ALREADY_REGISTERED',
  BOT_SECRET_INVALID: 'BOT_SECRET_INVALID',
  SLUG_TAKEN: 'SLUG_TAKEN',
  FORBIDDEN: 'FORBIDDEN',
  ORG_SUSPENDED: 'ORG_SUSPENDED',
  CONSENT_REQUIRED: 'CONSENT_REQUIRED',
  RE_CONSENT_REQUIRED: 'RE_CONSENT_REQUIRED',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
